<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Simple ASP.NET CRUD</title>
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen"> 
<style>
input {
	margin-top:7px;
}
</style>

</head>

<body>

<div class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
 
        <div class="navbar-header">
            <a class="navbar-brand" href="#">SIMPLE ASP.NET CRUD</a>
        </div>
 
    </div>
</div>